"""initial

Revision ID: 4d6cf5a53efc
Revises: 
Create Date: 2022-04-01 14:02:59.563123

"""
from alembic import op
import sqlalchemy as sa
import app
import app.models.task


# revision identifiers, used by Alembic.
revision = '4d6cf5a53efc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(), nullable=True),
    sa.Column('softwaretype', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('time_created', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('last_access', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_description'), 'software', ['description'], unique=False)
    op.create_index(op.f('ix_software_id'), 'software', ['id'], unique=False)
    op.create_index(op.f('ix_software_name'), 'software', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('surname', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.Integer(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('last_update', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(), nullable=True),
    sa.Column('implant_id', sa.String(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('os_version', sa.String(length=256), nullable=False),
    sa.Column('machine_name', sa.String(length=256), nullable=False),
    sa.Column('architecture', sa.String(length=256), nullable=False),
    sa.Column('source_address', sa.String(length=256), nullable=False),
    sa.Column('wan_address', sa.String(length=256), nullable=True),
    sa.Column('parent', sa.String(length=256), nullable=True),
    sa.Column('time_created', sa.Integer(), nullable=True),
    sa.Column('time_lastcheckin', sa.Integer(), nullable=True),
    sa.Column('time_lastassignment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_id'), 'target', ['id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('args', app.models.task.TextPickleType(length=256), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('return_data', sa.String(), nullable=True),
    sa.Column('return_code', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.Integer(), nullable=False),
    sa.Column('time_assigned', sa.Integer(), nullable=False),
    sa.Column('time_started', sa.Integer(), nullable=True),
    sa.Column('time_finished', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submitter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_target_id'), table_name='target')
    op.drop_table('target')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_software_name'), table_name='software')
    op.drop_index(op.f('ix_software_id'), table_name='software')
    op.drop_index(op.f('ix_software_description'), table_name='software')
    op.drop_table('software')
    # ### end Alembic commands ###
